"""phase 2: connector credentials

Revision ID: 566b7668189b
Revises: a6825efe81e0
Create Date: 2026-08-30 06:29:31.380327
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # autogenerate emits pgvector types without importing them
from sqlalchemy.dialects import postgresql

revision: str = '566b7668189b'
down_revision: str | None = 'a6825efe81e0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_accounts', sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_accounts', 'credentials')
    # ### end Alembic commands ###
