"""phase 2: extraction cache

Revision ID: a6825efe81e0
Revises: b143fa8a55de
Create Date: 2026-08-30 06:14:54.005817
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # autogenerate emits pgvector types without importing them


revision: str = 'a6825efe81e0'
down_revision: str | None = 'b143fa8a55de'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraction_cache',
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('cache_key', name=op.f('pk_extraction_cache'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extraction_cache')
    # ### end Alembic commands ###
